version: '3.8'

services:
  ip-monitor:
    build: .
    container_name: ip-network-monitor
    ports:
      - "8000:8000"
    # volumes:
      # - ./data:/app/data
    restart: unless-stopped
    network_mode: "host"
    cap_add:
      - NET_RAW
      - NET_ADMIN
    environment:
      - TZ=Asia/Shanghai
